// Generated by `cargo test -p toolog-app`. Do not edit.
//
// Every type and command here is derived from the Rust definitions in
// crates/toolog-app/src/commands.rs; editing this file by hand only
// makes it disagree with what the application actually accepts.

import { invoke } from "@tauri-apps/api/core";

export type ToolCall = { tool_use_id: string, session_id: string | null, prompt_id: string | null, message_uuid: string | null, parent_uuid: string | null, is_sidechain: boolean | null, 
/**
 * Subagent *instance*. Present on every sidechain record and no
 * main-thread record, so it is the reliable discriminator.
 */
agent_id: string | null, 
/**
 * Subagent *type* (`Explore`, `general-purpose`). Best-effort: it appears
 * on only some records, and is backfilled per `agent_id`.
 */
agent_name: string | null, tool_name: string | null, tool_kind: string | null, mcp_server: string | null, mcp_tool: string | null, called_at: number | null, completed_at: number | null, input_json: string | null, input_summary: string | null, target_path: string | null, result_json: string | null, result_text: string | null, result_size: number | null, success: boolean | null, duration_ms: number | null, error_type: string | null, decision: string | null, decision_source: string | null, permission_mode: string | null, provenance: number, };

export type Session = { session_id: string, project_path: string | null, transcript_path: string | null, cwd: string | null, git_branch: string | null, cc_version: string | null, entrypoint: string | null, 
/**
 * A session label such as `host-password-reset-flow`, from `agent-name`
 * records. **Not** subagent attribution — see [`ToolCall::agent_id`].
 */
agent_name: string | null, slug: string | null, first_seen: number | null, last_seen: number | null, };

export type FileChange = { tool_use_id: string, file_path: string, lines_added: number, lines_removed: number, patch_json: string | null, };

export type TimelineFilter = { session_id: string | null, 
/**
 * Only calls whose session the store never learned.
 *
 * A group the timeline can show but `session_id` cannot name, and without
 * it "expand that group" would quietly widen to every row.
 */
session_unknown: boolean | null, project_path: string | null, tool_name: string | null, since: number | null, until: number | null, success: boolean | null, is_sidechain: boolean | null, decision: string | null, decision_source: string | null, permission_mode: string | null, 
/**
 * One subagent instance.
 */
agent_id: string | null, 
/**
 * `true`: only main-thread calls. `false`: only subagent calls.
 *
 * Reads `agent_id`, which is present on every sidechain call and no
 * main-thread one, rather than `is_sidechain`, which is null on any row
 * the transcript lane has not witnessed.
 */
main_thread: boolean | null, 
/**
 * Free text, as typed. Sanitized into an FTS5 expression before use —
 * `rm -rf` is a search term here, not an operator.
 */
query: string | null, 
/**
 * Rows witnessed by exactly this set of lanes.
 *
 * Exact, not a mask. A mask can say "the OTLP lane saw this" but not "and
 * the transcript lane did not", and it was a mask that let `--rejected`
 * quietly mean "every call OTEL witnessed" for two phases.
 */
provenance: number | null, };

export type Page = { limit: number, offset: number, };

export type Reconciliation = { 
/**
 * Seen by both lanes.
 */
both: number, 
/**
 * Transcript only: the OTLP lane missed it. A gap in collection.
 */
transcript_only: number, 
/**
 * OTLP only: no transcript body was ever written for this call.
 */
otel_only: number, 
/**
 * Calls the OTLP lane recorded a refusal for.
 *
 * Counted from `decision`, not from provenance. Phase 4 measured a real
 * denial and found it in **both** lanes: the transcript keeps the
 * `tool_use` block and a `tool_result` whose body is the refusal message.
 * Only OTEL says *who* refused and *why*, as structured data — so a
 * rejection is identified by this column, never by a missing transcript.
 */
rejected: number, };

export type TimelineRow = { call: ToolCall, project_path: string | null, git_branch: string | null, 
/**
 * An FTS `snippet()` with the match bracketed. `None` unless the filter
 * carried a search term — the match may be in `result_text`, which the
 * row itself never shows.
 */
snippet: string | null, 
/**
 * Lines this call added and removed, summed over the files it touched.
 *
 * `None` for a call that changed no file. An `Edit` row without its size
 * is the one row in this list that says nothing about what it did.
 */
lines_added: number | null, lines_removed: number | null, };

export type AgentGroup = { 
/**
 * The subagent *instance*. Present on every sidechain call.
 */
agent_id: string, 
/**
 * The subagent *type* (`Explore`, `general-purpose`), where it is known.
 */
agent_name: string | null, calls: number, first_at: number | null, last_at: number | null, };

export type SessionGroup = { 
/**
 * `None` for calls whose session the store never learned — an OTLP event
 * that arrived before any transcript line named the session.
 */
session_id: string | null, project_path: string | null, git_branch: string | null, slug: string | null, cc_version: string | null, calls: number, main_thread_calls: number, failures: number, refusals: number, first_at: number | null, last_at: number | null, 
/**
 * Sum of `api_request.cost_usd_micros` for the session.
 *
 * `None`, never `0`, when the OTLP lane never saw this session: imported
 * history has no cost data at all, and a zero would read as free.
 */
cost_usd_micros: number | null, agents: Array<AgentGroup>, };

export type Facets = { projects: Array<string>, tools: Array<string>, decision_sources: Array<string>, permission_modes: Array<string>, agents: Array<string>, };

export type Totals = { raw_events: number, sessions: number, tool_calls: number, file_changes: number, api_requests: number, 
/**
 * Sum of `cost_usd_micros`. OTLP only — always zero for backfilled history,
 * which the UI must say rather than render as a real zero.
 */
cost_usd_micros: number, input_tokens: number, output_tokens: number, first_call_at: number | null, last_call_at: number | null, };

export type ToolUsage = { tool_name: string, calls: number, failures: number, 
/**
 * Null until the OTLP lane has seen these calls.
 */
p50_ms: number | null, p95_ms: number | null, };

export type IngestSummary = { 
/**
 * Distinct transcript files with at least one stored record.
 */
transcript_files: number, transcript_records: number, otlp_records: number, 
/**
 * When anything was last stored, in milliseconds since the epoch.
 */
last_ingest_at: number | null, };

export type CounterSnapshot = { batches: number, records: number, dropped: number, rejected_bodies: number, paused_drops: number, };

export type Status = { 
/**
 * The address the receiver actually bound, which may not be the preferred
 * one.
 */
endpoint: string, listening: boolean, paused: boolean, counters: CounterSnapshot, 
/**
 * Records stored since local midnight.
 */
events_today: number, tool_calls: number, database: string, 
/**
 * True when the receiver had to fall back from the preferred port, which
 * means Claude Code's configuration needs rewriting to match.
 */
port_changed: boolean, };

export type Summary = { files: number, lines: number, stored: number, duplicates: number, tool_uses: number, sessions: number, };

export type Format = "json" | "jsonl" | "csv" | "markdown";

export type ToolCallDetail = { call: ToolCall, 
/**
 * Files this call changed, with their diffs.
 */
file_changes: Array<FileChange>, 
/**
 * The envelope the call ran inside: cwd, branch, Claude Code version.
 * `None` for a call whose session the store never learned.
 */
session: Session | null, };

export type SourceView = { 
/**
 * The transcript that recorded this call.
 */
path: string, 
/**
 * 1-based line number, when the file is still on disk to count into.
 */
line: number | null, 
/**
 * Whether that file is still there. Transcripts are Claude Code's to
 * delete, and the stored record outlives them.
 */
exists: boolean, 
/**
 * The stored transcript line, verbatim. This is the evidence; the file is
 * a convenience.
 */
body: string, };

export type Stats = { totals: Totals, tools: Array<ToolUsage>, 
/**
 * Lane divergence. Not a footnote: OTEL-only calls are refusals.
 */
reconciliation: Reconciliation, };

export type Setup = { configured: boolean, listening: boolean, endpoint: string, settings_path: string, transcripts_dir: string, transcript_files: number, ingested_files: number, agent_supported: boolean, agent_installed: boolean, problems: Array<string>, 
/**
 * The rendered `toolog doctor` output, verbatim.
 */
report: string, };

export function queryTimeline(filter: TimelineFilter, page: Page): Promise<Array<TimelineRow>> {
  return invoke("query_timeline", { filter, page });
}

export function timelineGroups(filter: TimelineFilter): Promise<Array<SessionGroup>> {
  return invoke("timeline_groups", { filter });
}

export function facets(): Promise<Facets> {
  return invoke("facets");
}

export function timelineCount(filter: TimelineFilter): Promise<number> {
  return invoke("timeline_count", { filter });
}

export function getToolCall(toolUseId: string): Promise<ToolCallDetail | null> {
  return invoke("get_tool_call", { toolUseId });
}

export function getSource(toolUseId: string): Promise<SourceView | null> {
  return invoke("get_source", { toolUseId });
}

export function listSessions(page: Page): Promise<Array<Session>> {
  return invoke("list_sessions", { page });
}

export function stats(): Promise<Stats> {
  return invoke("stats");
}

export function collectorStatus(): Promise<Status> {
  return invoke("collector_status");
}

export function setPaused(paused: boolean): Promise<Status> {
  return invoke("set_paused", { paused });
}

export function runBackfill(): Promise<Summary> {
  return invoke("run_backfill");
}

export function exportCalls(filter: TimelineFilter, format: Format, limit: number | null): Promise<string> {
  return invoke("export_calls", { filter, format, limit });
}

export function saveExport(filter: TimelineFilter, format: Format, limit: number | null): Promise<string | null> {
  return invoke("save_export", { filter, format, limit });
}

export function doctorStatus(): Promise<Setup> {
  return invoke("doctor_status");
}

export function applyDoctorFix(): Promise<Setup> {
  return invoke("apply_doctor_fix");
}

export function setLoginAgent(install: boolean): Promise<Setup> {
  return invoke("set_login_agent", { install });
}

export function revealLogs(): Promise<null> {
  return invoke("reveal_logs");
}

export function revealTranscript(path: string): Promise<null> {
  return invoke("reveal_transcript", { path });
}

