//! Generating `ui/src/bindings.ts` from the Rust types.
//!
//! Task 4.9 asks for a boundary that cannot drift. The generator is the only
//! writer of that file, and [`check`] — run as a test — fails when what is
//! checked in differs from what the current Rust would produce. So a change to
//! a command's signature or to any type that crosses the IPC boundary breaks
//! the build until the bindings are regenerated.
//!
//! Large integers are emitted as `number`, not `bigint`. Rust's `i64` is the
//! type of every timestamp and counter here; serde writes them as JSON numbers
//! and `JSON.parse` produces a `number`, so `bigint` would describe a value the
//! frontend never actually receives. Our largest magnitudes are millisecond
//! timestamps, comfortably inside the 2^53 a double represents exactly.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use ts_rs::TS;

/// One command, as the frontend sees it.
pub(crate) struct Signature {
    pub(crate) rust_name: &'static str,
    pub(crate) args: Vec<(&'static str, String)>,
    pub(crate) ret: String,
}

/// The ts-rs settings the bindings are generated under.
fn config() -> ts_rs::Config {
    ts_rs::Config::default().with_large_int("number")
}

/// Where the generated file lives.
pub(crate) fn output_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("ui")
        .join("src")
        .join("bindings.ts")
}

/// Every type that crosses the boundary, declared once.
macro_rules! type_decls {
    ($cfg:expr, $($ty:ty),* $(,)?) => {{
        let mut out = String::new();
        $(
            let _ = writeln!(out, "export {}\n", <$ty as TS>::decl($cfg));
        )*
        out
    }};
}

/// Render the whole bindings file.
#[must_use]
pub(crate) fn generate() -> String {
    let cfg = &config();

    let mut out = String::new();
    out.push_str(
        "// Generated by `cargo test -p toolog-app`. Do not edit.\n\
         //\n\
         // Every type and command here is derived from the Rust definitions in\n\
         // crates/toolog-app/src/commands.rs; editing this file by hand only\n\
         // makes it disagree with what the application actually accepts.\n\n\
         import { invoke } from \"@tauri-apps/api/core\";\n\n",
    );

    out.push_str(&type_decls!(
        cfg,
        toolog_core::model::ToolCall,
        toolog_core::model::Session,
        toolog_core::model::FileChange,
        toolog_core::model::TimelineFilter,
        toolog_core::model::Page,
        toolog_core::query::TimelineRow,
        toolog_core::query::AgentGroup,
        toolog_core::query::SessionGroup,
        toolog_core::query::Facets,
        toolog_core::query::BucketSize,
        toolog_core::query::Bucket,
        toolog_core::query::Histogram,
        toolog_core::query::IngestSummary,
        toolog_core::rules::Severity,
        toolog_core::rules::Scope,
        toolog_core::rules::Dismissal,
        toolog_core::rules::Finding,
        toolog_core::rules::ProjectRisk,
        toolog_cli::prefs::Prefs,
        toolog_otlp::server::CounterSnapshot,
        toolog_cli::capture::Status,
        toolog_cli::commands::Summary,
        toolog_cli::commands::Format,
        crate::commands::ToolCallDetail,
        crate::commands::SourceView,
        crate::commands::RiskReview,
        crate::commands::Setup,
        crate::commands::UninstallPlan,
        crate::commands::UninstallOutcome,
    ));

    for sig in crate::commands::signatures(cfg) {
        let params = sig
            .args
            .iter()
            .map(|(name, ty)| format!("{}: {ty}", camel(name)))
            .collect::<Vec<_>>()
            .join(", ");
        // Tauri converts snake_case parameter names to camelCase on the way in.
        let payload = sig
            .args
            .iter()
            .map(|(name, _)| camel(name))
            .collect::<Vec<_>>()
            .join(", ");
        let payload = if payload.is_empty() {
            String::new()
        } else {
            format!(", {{ {payload} }}")
        };

        let _ = writeln!(
            out,
            "export function {}({params}): Promise<{}> {{\n  \
             return invoke(\"{}\"{payload});\n}}\n",
            camel(sig.rust_name),
            sig.ret,
            sig.rust_name
        );
    }

    out
}

/// `tool_use_id` to `toolUseId`.
fn camel(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper = false;
    for c in name.chars() {
        if c == '_' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// Write the bindings to disk.
pub(crate) fn write() -> std::io::Result<PathBuf> {
    let path = output_path();
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(&path, generate())?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regenerate on every test run, so the file is never stale by accident.
    #[test]
    fn the_checked_in_bindings_match_the_rust() {
        let generated = generate();
        let path = output_path();
        let current = std::fs::read_to_string(&path).unwrap_or_default();

        if current != generated {
            write().expect("write bindings");
            panic!(
                "{} was out of date and has been regenerated. \
                 Review the diff and commit it.",
                path.display()
            );
        }
    }

    #[test]
    fn timestamps_are_numbers_because_that_is_what_arrives() {
        let ts = generate();
        assert!(
            !ts.contains("bigint"),
            "serde sends i64 as a JSON number; bigint would describe a value the UI never sees"
        );
        assert!(ts.contains("called_at: number | null"));
    }

    #[test]
    fn every_command_is_wrapped_and_every_type_it_names_is_declared() {
        let ts = generate();
        let cfg = config();

        for sig in crate::commands::signatures(&cfg) {
            let wrapper = format!("export function {}(", camel(sig.rust_name));
            assert!(ts.contains(&wrapper), "{} has no wrapper", sig.rust_name);
            assert!(
                ts.contains(&format!("invoke(\"{}\"", sig.rust_name)),
                "{} does not invoke its own name",
                sig.rust_name
            );

            for ty in sig
                .args
                .iter()
                .map(|(_, t)| t)
                .chain(std::iter::once(&sig.ret))
            {
                for name in referenced_types(ty) {
                    assert!(
                        ts.contains(&format!("export type {name} =")),
                        "{} names {name}, which is not declared in the bindings",
                        sig.rust_name
                    );
                }
            }
        }
    }

    /// The named types inside a TypeScript type expression.
    fn referenced_types(ts_type: &str) -> Vec<String> {
        const BUILTINS: &[&str] = &["Array", "string", "number", "boolean", "null", "void"];
        ts_type
            .split(|c: char| !c.is_alphanumeric() && c != '_')
            .filter(|s| {
                !s.is_empty()
                    && s.chars().next().is_some_and(char::is_uppercase)
                    && !BUILTINS.contains(s)
            })
            .map(ToString::to_string)
            .collect()
    }

    /// A wrapper named after a reserved word is a syntax error the Rust side
    /// would never notice. Catch it here rather than in the browser.
    #[test]
    fn no_generated_name_collides_with_a_typescript_keyword() {
        const RESERVED: &[&str] = &[
            "export",
            "import",
            "default",
            "class",
            "function",
            "return",
            "new",
            "delete",
            "typeof",
            "void",
            "in",
            "instanceof",
            "await",
            "yield",
            "const",
            "let",
            "var",
            "switch",
            "case",
            "catch",
            "finally",
            "for",
            "while",
            "do",
            "if",
            "else",
            "this",
            "super",
            "throw",
            "try",
            "with",
            "enum",
            "extends",
            "null",
            "true",
            "false",
        ];
        let cfg = config();
        for sig in crate::commands::signatures(&cfg) {
            let js = camel(sig.rust_name);
            assert!(
                !RESERVED.contains(&js.as_str()),
                "`{js}` is a TypeScript keyword; rename the command"
            );
            for (arg, _) in &sig.args {
                let js = camel(arg);
                assert!(
                    !RESERVED.contains(&js.as_str()),
                    "argument `{js}` of {} is a TypeScript keyword",
                    sig.rust_name
                );
            }
        }
    }

    #[test]
    fn argument_names_are_camel_cased_the_way_tauri_delivers_them() {
        assert_eq!(camel("tool_use_id"), "toolUseId");
        assert_eq!(camel("filter"), "filter");
        assert_eq!(camel("run_backfill"), "runBackfill");
        assert!(generate().contains("getToolCall(toolUseId: string)"));
    }
}
